name: Build on Develop

on:
  push:
    branches:
      - develop

jobs:
  build_only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install # Or any other build commands
        npm run build
